### ISSUE TITLE
Meta-data issues with stm-supply-0.1.0.0

### ISSUE THREAD

**Issue by hvr** [caneroj1/stm-supply#1]
I noticed your recent package upload to Hackage as it was flagged by the matrix buildbot due to  packaging meta-data issues:

 - The `description` ("Please see README.md") is not proper description for your package (and Hackage already shows a link to the README at the end of the description if the README exists, so that phrase is completely redundant), and hence this will cause poor experience for users. See also [this posting](https://mail.haskell.org/pipermail/haskell-cafe/2016-November/125541.html) for more details.

 - The lower bound on `base` is inaccurate, e.g. with GHC 7.8.4 / base-4.7:

```
Configuring component lib from stm-supply-0.1.0.0
Preprocessing library stm-supply-0.1.0.0...
[1 of 1] Compiling Control.Concurrent.STMSupply ( src/Control/Concurrent/STMSupply.hs, /tmp/stm-supply-0.1.0.0/dist-newstyle/build/x86_64-linux/ghc-7.8.4/stm-supply-0.1.0.0/build/Control/Concurrent/STMSupply.o )

src/Control/Concurrent/STMSupply.hs:19:25: Not in scope: ‘<$>’

src/Control/Concurrent/STMSupply.hs:24:24: Not in scope: ‘<$>’

src/Control/Concurrent/STMSupply.hs:32:29: Not in scope: ‘<$>’

src/Control/Concurrent/STMSupply.hs:33:29: Not in scope: ‘<$>’
```

**Comment by caneroj1** [comment]
Thanks for the heads up! I haven't set up my usual Travis CI stuff yet.

I should be able to take care of these later today.

**Comment by caneroj1** [comment]
Fixed the build error and added Travis CI. Builds include GHC 7.8.4.

Also updated the description.

**Comment by hvr** [comment]
Thanks!

Fyi, i've fixed up the `.cabal` file for the existing release on Hackage accordingly: https://hackage.haskell.org/package/stm-supply-0.1.0.0/revisions/ to prevent cabal from selecting bad install plans.
